
[build]
  command = "npm run build"
  publish = "dist"

# SPA redirect so deep links resolve to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static dataset files if served from /public/data
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
